development:
  adapter: postgresql
  encoding: utf8
  database: site_lz_development
  host: localhost
  user: helioadson
  password: 123456
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  encoding: utf8
  database: site_lz_test
  host: localhost
  user: helioadson
  password: 123456
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  encoding: utf8
  database: site_lz_development
  host: localhost
  user: helioadson
  password: 123456
  pool: 5
  timeout: 5000
  template: template0