development:
  adapter: postgresql
  database: site_lz_development
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  database: site_lz_test
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: site_lz_production
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0